AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Guess related lambda functions

Parameters:
  ScansTableName:
    Type: String
  ScansTableArn:
    Type: String
  GuessesTableName:
    Type: String
  GuessesTableArn:
    Type: String
  GuessResultTopicArn:
    Type: String
  GuessResultTopicName:
    Type: String
  ScoreGuessQueueArn:
    Type: String
  NotifyUserQueueArn:
    Type: String
  LeaderboardQueueArn:
    Type: String
  UserPoolArn:
    Type: String

Globals:
  Function:
    CodeUri: ../
    Timeout: 10
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        SCANS_TABLE: !Ref ScansTableName
        GUESSES_TABLE: !Ref GuessesTableName
        GUESS_RESULT_TOPIC_ARN: !Ref GuessResultTopicArn
    LoggingConfig:
      LogFormat: JSON
  Api:
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !Ref UserPoolArn

Resources:
  SubmitGuessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: submitGuessHandler.handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GuessesTableName
        - DynamoDBReadPolicy:
            TableName: !Ref ScansTableName

      Events:
        SubmitGuess:
          Type: Api
          Properties:
            Path: /scans/{scanId}/guess
            Method: post

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        OutExtension:
          - .js=.js
        Target: es2020
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/submitGuess/submitGuessHandler.ts

  GetGuessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getGuessHandler.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GuessesTableName

      Events:
        GetGuess:
          Type: Api
          Properties:
            Path: /scans/{scanId}/guess
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        OutExtension:
          - .js=.js
        Target: es2020
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/getGuess/getGuessHandler.ts

  ScoreGuessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: scoreGuessHandler.handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GuessesTableName
        - SNSPublishMessagePolicy:
            TopicName: !Ref GuessResultTopicName

      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref ScoreGuessQueueArn
            BatchSize: 10

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        OutExtension:
          - .js=.js
        Target: es2020
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/scoreGuess/scoreGuessHandler.ts

  NotifyUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: notifyUser.handler
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref NotifyUserQueueArn
            BatchSize: 10

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        OutExtension:
          - .js=.js
        Target: es2020
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/notifyUser/notifyUser.ts

  LeaderboardFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: leaderboard.handler
        Policies:
          - SSMParameterReadPolicy:
              ParameterName: scan-guess/db-url
        Events:
          SQSEvent:
            Type: SQS
            Properties:
              Queue: !Ref LeaderboardQueueArn
              BatchSize: 10
      Metadata:
        BuildMethod: esbuild
        BuildProperties:
          Format: cjs
          OutExtension:
            - .js=.js
          Target: es2020
          Minify: false
          Sourcemap: true
          EntryPoints:
            - src/leaderboard/leaderboard.ts
