AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Scan Guess App

Resources:
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure/auth.yaml

  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure/storage.yaml

  QueuesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure/queues.yaml

  ScansStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: functions/scans.yaml
      Parameters:
        ScansTableName: !GetAtt StorageStack.Outputs.ScansTableName
        ScansTableArn: !GetAtt StorageStack.Outputs.ScansTableArn
        ScansTableStreamArn: !GetAtt StorageStack.Outputs.ScansTableStreamArn
        GuessesTableName: !GetAtt StorageStack.Outputs.GuessesTableName
        GuessesTableArn: !GetAtt StorageStack.Outputs.GuessesTableArn
        ScansBucketName: !GetAtt StorageStack.Outputs.ScansBucketName
        ScoreGuessQueueUrl: !GetAtt QueuesStack.Outputs.ScoreGuessQueueUrl
        ScoreGuessQueueName: !GetAtt QueuesStack.Outputs.ScoreGuessQueueName
        UserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn

  GuessesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: functions/guesses.yaml
      Parameters:
        ScansTableName: !GetAtt StorageStack.Outputs.ScansTableName
        ScansTableArn: !GetAtt StorageStack.Outputs.ScansTableArn
        GuessesTableName: !GetAtt StorageStack.Outputs.GuessesTableName
        GuessesTableArn: !GetAtt StorageStack.Outputs.GuessesTableArn
        GuessResultTopicArn: !GetAtt QueuesStack.Outputs.GuessResultTopicArn
        GuessResultTopicName: !GetAtt QueuesStack.Outputs.GuessResultTopicName
        ScoreGuessQueueArn: !GetAtt QueuesStack.Outputs.ScoreGuessQueueArn
        NotifyUserQueueArn: !GetAtt QueuesStack.Outputs.NotifyUserQueueArn
        LeaderboardQueueArn: !GetAtt QueuesStack.Outputs.LeaderboardQueueArn
        UserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn

Outputs:
  UserPoolId:
    Value: !GetAtt AuthStack.Outputs.UserPoolId
  UserPoolClientId:
    Value: !GetAtt AuthStack.Outputs.UserPoolClientId
